### ISSUE TITLE
Devices not showing up

### ISSUE THREAD

**Issue by mario-to-lowercase** [awahlig/homebridge-casambi#1]
Hi the devices are showing up on my homebridge but not on my phone. And on homebridge i cant change the state.

Im running homebridge on a synology rs1219+ indside docker

**Comment by awahlig** [comment]
Can you send me your homebridge log file? Particularly from startup (when devices are scanned) and when you try to change the state.

Devices not showing up on your phone sounds like an issue unrelated to the plugin. Do you have any other plugins? Do they work correctly?

**Comment by mario-to-lowercase** [comment]
The log folder is completley empty.

The issue with devices not showing up is a homebridge issue and has nothing to do with the plugin your right.
But the state wont change.

Here the console if it helps
![Bildschirmfoto 2020-09-01 um 11 19 04](https://user-images.githubusercontent.com/34585017/91832472-bada7900-ec45-11ea-91b7-d2a46087b413.png)

EDIT: The devices now showing up with "No response"

**Comment by awahlig** [comment]
Could you pull the latest master, run homebridge in [debug mode](https://github.com/homebridge/homebridge/wiki/Basic-Troubleshooting) and capture the log again?

I've added some more logging to better debug unknown devices. So far I've only tested the plugin with my Occhio lamps so it's possible your lamps are somehow different. The new log should tell us if they are. The most important part starts with "Found x unit(s) in the network y".

Also, try to turn the lamps on/off using the switches on the lamps, while homebridge is running. The log in debug mode should show homebridge being notified about these events by the Casambi Cloud, which would confirm that the gateway is working properly and show us how they're reporting their new state.

**Comment by mario-to-lowercase** [comment]
Thanks for the help so far.
Plugin is updated and debug mode is enabled.

Now it looks like this
![Bildschirmfoto 2020-09-03 um 20 10 02](https://user-images.githubusercontent.com/34585017/92151563-a4891480-ee21-11ea-9a3f-ac55ce77f5b8.png)

You can see the protocol says unsupported control type.
These are the controlls in the app
![screen](https://user-images.githubusercontent.com/34585017/92151636-c5516a00-ee21-11ea-811d-dfe1d7af90e2.jpeg)

**Comment by awahlig** [comment]
Looks like you're not running the latest code. I probably wasn't clear that I wanted you to overwrite the plugin files with the latest from github instead of updating to the latest release.

To make this easier, I made a new release now, v0.2.3. You should be able to update to it using the homebridge web ui. Please make sure you're running v0.2.3 and try to get the debug log again.

Sorry for the confusion.

Yes, the device "Küche" is unsupported and shouldn't be showing up in homebridge/homekit. Right now, the plugin only supports devices of type "Luminaire" (a lamp) but this device is of type "Driver". What does it do exactly?

The other devices (PC, Bett, Tisch and HYPRO-F) are not throwing this error so they should be of type "Luminaire". Let's try to figure out why they don't work first.

Edit:

Hmm, your log does show the "Send controlUnit" messages which mean that commands are being sent to the devices to turn them on/off. Normally, this should be followed by a notification from the device that its state has changed. This is missing here. A common reason for this, from my experience, is a problem with the gateway device. Make sure that the app is open on the gateway and that the lamp you're trying to control is in the Bluetooth range of the gateway.

**Comment by mario-to-lowercase** [comment]
Oh im sorry i misunderstood your last reply

Here is the new log
[homebridge.log.txt](https://github.com/awahlig/homebridge-casambi/files/5170664/homebridge.log.txt)

Now i noticed that sometimes i cant change the state of the luminare inside the app

The device "Küche" is also a luminare but it has a driver with integrated casambi module inside (like [THIS](https://www.watt24.com/media/ee/21/4b/1592163204/TCI-LED-Treiber-PROFESSIONALE-CASAMBI-BI-127631-1_1592163194_8.jpg)) and the other luminaires only have the casambi module.

EDIT: Now its kind of working. I noticed that i dindt had the gateway option enabled.
The device "Hypro" is now working but not the devicces "PC" and "Bett"

Here the new log
[NEWhomebridge.log.txt](https://github.com/awahlig/homebridge-casambi/files/5170708/NEWhomebridge.log.txt)

**Comment by awahlig** [comment]
Thanks for the logs.

All devices (except "Küche") should work. They all support the "dimmer" control which is used to set the brightness of the light.

It looks like the Driver lamp ("Küche") also exposes the "dimmer" control so adding support for it should be easy. I'll do that in the next version.

The reason why controlling the lights didn't/doesn't work seems to be a problem with communication between the lights and the gateway device.

Do you have a dedicated gateway device that you keep close to the lights? That's what I have, I bought a cheap Android tablet and have it hidden in a cabinet, plugged into a charger 24/7. It's running the Casambi app and it's configured as a gateway in the network settings of the Casambi app. Make sure you can control the lights from the gateway itself. This will tell you that the lights are in the Bluetooth range of the gateway.

If that works, the plugin should work as well.

Another way to test the gateway is to try to use the app on your phone to control the lights while you're not home. It should work now because the app will talk to the gateway device to control the lights. You can test this without leaving your home by disabling WiFi and Bluetooth on your phone and letting it use LTE.

The plugin basically does the same thing so it should work.

**Comment by mario-to-lowercase** [comment]
Ok now it almost works...

The only luminaire wich is not working is the "HYPRO" i think its because of the unsupported switch types.

But thanks for the support. 
If you have a paypal link or something simillar please send it to me i want to send you a little thank you :)

**Comment by awahlig** [comment]
Hmm, I can see HYPRO working correctly in the log file:

```
[9/3/2020, 9:12:20 PM] [Casambi] Set characteristic On of unit HYPRO-F to true
[9/3/2020, 9:12:20 PM] [Casambi] Send controlUnit for HYPRO-F { Dimmer: { value: 1 } }
[9/3/2020, 9:12:20 PM] [Casambi] Received unitChanged for HYPRO-F {
  controls: [
    { type: 'Dimmer', value: 1 },
```

The first line is the light being turned on in HomeKit, followed by a command being sent to the light and finally a confirmation coming back that the light is on now.

Btw, you should also be able to set the colour temperature for HYPRO through HomeKit.

The other switches (in-/direct, diffusion) are not supported because of HomeKit limitations.

And thank you for the kind offer but there's no need to give me anything. Have a nice weekend :)
