### ISSUE TITLE
Support For More Bulbs

### ISSUE THREAD

**Issue by SCHUNK-SOLUTIONS** [awahlig/homebridge-casambi#7]
occhio sento verticale
occhio mito largo
occhio mito sospesso

**Comment by awahlig** [comment]
Hi, can you elaborate what the issue is?

I have tested the plugin with the Occhio Mito Largo lamp so it should work fine, the other two are similar so should be good too.

If you’re asking about support for the “vertical” feature of these lamps (up/down light), you can enable that in the plugin settings (_Up/down luminaire control_). It adds a second lamp to HomeKit and you can use its brightness control to select the direction of the light. It’s a workaround because of HomeKit limitations.

**Comment by SCHUNK-SOLUTIONS** [comment]
It Does Not Work to Turn the Lamps on or off

**Comment by SCHUNK-SOLUTIONS** [comment]
When i Change The state of an bulb nothing does apear on the terminal
Normaly with other plugins i see wen something gets changed

**Comment by SCHUNK-SOLUTIONS** [comment]
Homebridge LOG
[homebridge.log](https://github.com/awahlig/homebridge-casambi/files/5888085/homebridge.log)

**Comment by awahlig** [comment]
Your log shows many network errors when trying to connect to the Casambi API. The plugin requires internet connection and will not work without it.

Make sure you’re seeing
**Successfully logged in to Casambi network**
and
**Connection successful**
events after startup.

The plugin doesn’t log light on/off events by default. You have to run Homebridge in debug mode to see them.

When it is connected to the Casambi API and you turn a light on/off in HomeKit, the plugin will send a command to the API and log a **controlUnit** event in debug mode. If everything works, the light should turn on/off and a confirmation should be received by the plugin (a **unitChanged** event will be logged).

**Comment by SCHUNK-SOLUTIONS** [comment]
Thanks for your answer!
Ok how do i force it?
key, email an password is right. why doesnt it connect?

**Comment by awahlig** [comment]
The error seems to indicate a problem with the DNS.

What happens when you try to ping the server?

```
$ ping door.casambi.com
```

**Comment by SCHUNK-SOLUTIONS** [comment]
no problems pingning:
/homebridge # ping door.casambi.com
PING door.casambi.com (84.22.117.218) 56(84) bytes of data.
64 bytes from casambi2.tilaa.cloud (84.22.117.218): icmp_seq=1 ttl=50 time=43.1 ms
64 bytes from casambi2.tilaa.cloud (84.22.117.218): icmp_seq=2 ttl=50 time=47.1 ms
64 bytes from casambi2.tilaa.cloud (84.22.117.218): icmp_seq=3 ttl=50 time=40.7 ms
64 bytes from casambi2.tilaa.cloud (84.22.117.218): icmp_seq=4 ttl=50 time=41.0 ms
64 bytes from casambi2.tilaa.cloud (84.22.117.218): icmp_seq=5 ttl=50 time=42.6 ms
64 bytes from casambi2.tilaa.cloud (84.22.117.218): icmp_seq=6 ttl=50 time=40.2 ms
64 bytes from casambi2.tilaa.cloud (84.22.117.218): icmp_seq=7 ttl=50 time=41.2 ms

**Comment by awahlig** [comment]
That’s good. Can try try this?
```
$ curl -v https://door.casambi.com
```

It should connect and return a 401 error.

If that all works then Homebridge should be connecting as well. Maybe the problem was intermittent?

In that case I suggest you run Homebridge in debug mode and look for the messages I mentioned before. First confirm the plugin is logging in to the Casambi API and then that it is sending the on/off commands out when you control the lights.

**Comment by SCHUNK-SOLUTIONS** [comment]
i think now im able to connect to the casambi server but i found a new problem.
When i add The Casambi Plugin to homebridge ind i want to add the Homebridge To my iPhone it says the device is inkompatible.
But when i remove the casambi config again all works fine.
![WhatsApp Image 2021-02-01 at 07 54 48](https://user-images.githubusercontent.com/37262853/106425926-f7b0d300-6464-11eb-9010-fcea868af275.jpeg)

**Comment by awahlig** [comment]
Another person reported a similar problem the other day but so far I’ve been unable to reproduce it.

If it works without the Casambi config, can you add Homebridge to the phone without the config first? Then, add the config back and restart Homebridge, it should pick up the new accessories.

**Comment by SCHUNK-SOLUTIONS** [comment]
Tried This too but then config ui x says home bridge is running perfect, but in the home app I just see device unavailable on all home bridge devices.

**Comment by SCHUNK-SOLUTIONS** [comment]
Could I help you reproduce it? Do you need logs or anything else?

**Comment by awahlig** [comment]
Can you try entering “1” in the “Ignore Fixture IDs” field in the plugin settings and then restarting Homebridge (or better yet, the entire machine).

This will make the plugin ignore/skip your “Hue outdoor spots”. Another user reported a similar issue and this helped.

**Comment by SCHUNK-SOLUTIONS** [comment]
ok i will check that! thanks!
i justt saw this error:
[2/2/2021, 10:41:18 AM] [Casambi] Connection successful
HAP Warning: Characteristic 000000AC-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic 000000AB-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.

is this a problem?

**Comment by SCHUNK-SOLUTIONS** [comment]
so the problem with inkompatible device is solved with the fixture ids, but i still cannot toggle them, when i change something it doesnt work/change on the lamp. same when i do it in config ui x

**Comment by awahlig** [comment]
Glad to hear.

Can you run Homebridge in debug mode, try to turn the lamps on/off and send me the log file?

Make sure the app is open on the phone/tablet that you set as Gateway in your Casambi network. It’s most likely some connectivity issue.

By the way, the HAP Warning is unrelated, it seems to refer to a Fan service which my plugin doesn’t use.

**Comment by SCHUNK-SOLUTIONS** [comment]
We Tried With app opened but nothing works.
[homebridge(1).log](https://github.com/awahlig/homebridge-casambi/files/5917616/homebridge.1.log)

**Comment by awahlig** [comment]
Hi, sorry for the delay.

The log file shows that the plugin works but the communication between the Casambi servers and the lights doesn’t work.

The way this communication works is like this:

_Home app_ -> _Homebridge_ -> _Casambi plugin_ -> _Casambi server_ -> _Gateway phone/device_ -> _Lights_

What I’m seeing in the log is that the plugin is sending commands to the Casambi server but never hears back. Most of the time this means that there’s a problem with the Gateway device.

**Make sure you have a Gateway device in the range of the lights at all times and that you’ve configured it in the app,**
as described here:
https://support.casambi.com/support/solutions/articles/12000017046-how-to-enable-a-gateway-for-a-network-
and here:
https://support.casambi.com/support/solutions/articles/12000074043-internet-gateway

When the Gateway is set up correctly, you should be able to control the lights remotely, when you’re away from the lights. My Homebridge plugin is using the same way to control the lights via the Internet.

**Can you test if you can control the lights remotely, when you're not home?** This is the best way to test that the Gateway works because it has nothing to do with Homebridge or the plugin. When you get that working, Homebridge should start working too.

Can you also describe your setup a bit more? What are you using as a Gateway?

---

Finally, here are the relevant pieces of the log with some explanations, if you're curious:

This line after startup confirms that the plugin connected to the Casambi servers. It should’ve been followed by the server sending the current state of all lights in the network. That isn't sent which most likely means the server doesn’t have that information because it can’t contact the lights via the Gateway.
```
[2/3/2021, 11:04:05 AM] [Casambi] Wire opened for network Wohnzimmer
```

This is logged when the plugin tries to turn the light on. The command is sent but no response containing the updated state of the light is returned, presumably because the server couldn’t contact the light.
```
[2/3/2021, 11:04:59 AM] [Casambi] Set characteristic On of unit Mito largo to true
[2/3/2021, 11:04:59 AM] [Casambi] Send controlUnit for Mito largo { Dimmer: { value: 1 } }
```

**Comment by SCHUNK-SOLUTIONS** [comment]
Now We Got it! It was the iPad app which had problems!

**Comment by SCHUNK-SOLUTIONS** [comment]
Is it Possible Te Ungroup the Lights with the Up and down Setting? :)

**Comment by awahlig** [comment]
Glad to hear you got it working!

Yes, you can separate the brightness and up/down controls into separate tiles. To do that, tap on the lamp in the Home app to open the controls, then tap on the gear/settings icon and then scroll down and select "Show as Separate Tiles".

Tap "Show as Single Tile" to group them again.

Note that the up/down control will only be visible when the "Up/down luminaire control" setting is enabled in the plugin config.
